##############################################################################
# @brief Build script module.
#
# @note This file is generated by BASIS from the template file
#       build_module.cmake.in which is part of the BASIS installation.
#
# Usage:
# @code
# cmake [-D<option>=<value>...] -P build_script.cmake
# @endcode
#
# @par Required arguments:
# <table border=0>
#   <tr>
#     @tp @b SOURCE_FILE=file @endtp
#     <td>Source file of executable or module script.</td>
#   </tr>
#   <tr>
#     @tp @b OUTPUT_FILE=file @endtp
#     <td>Output file configured for use in build tree.</td>
#   </tr>
# </table>
#
# @par Optional arguments:
# <table border=0>
#   <tr>
#     @tp @b INSTALL_FILE=file @endtp
#     <td>Output file configured for installation. Note that this file
#         is only created when also the final installation @p DESTINATION
#         is specified. Otherwise, this option is ignored.</td>
#   </tr>
#   <tr>
#     @tp @b DESTINATION=dir @endtp
#     <td>Installation directory. Required for configuration of script for
#         installation in order to convert paths to other project files to
#         proper relative paths. See basis_set_script_path() function.</td>
#   </tr>
#   <tr>
#     @tp @b OPTIONS=<opt1>[;<opt2>;...] @endtp
#     <td>Configuration options for basis_configure_script() excluding @c DESTINATION.</td>
#   </tr>
# </table>
#
# Copyright (c) 2012 University of Pennsylvania. All rights reserved.
# See http://www.rad.upenn.edu/sbia/software/license.html or COPYING file.
#
# Contact: SBIA Group <sbia-software at uphs.upenn.edu>
##############################################################################

cmake_minimum_required (VERSION 2.8.4)

# check required arguments
if (NOT SOURCE_FILE)
  message (FATAL_ERROR "Missing SOURCE_FILE argument!")
endif ()
if (NOT OUTPUT_FILE)
  message (FATAL_ERROR "Missing OUTPUT_FILE argument!")
endif ()
if (OPTIONS)
  list (REMOVE_ITEM OPTIONS DESTINATION)
else ()
  set (OPTIONS)
endif ()
# include definition of utility functions
include ("${CMAKE_CURRENT_LIST_DIR}/CommonTools.cmake")
# configure ("build") script - always touch files to update build timestamp
basis_configure_script ("${SOURCE_FILE}" "${OUTPUT_FILE}" ${OPTIONS})
if (INSTALL_FILE AND DESTINATION)
  basis_configure_script ("${SOURCE_FILE}" "${INSTALL_FILE}" DESTINATION "${DESTINATION}" ${OPTIONS})
endif ()
