##############################################################################
#! @file  TargetTools.cmake
#! @brief Functions and macros to add executable and library targets.
#!
#! Copyright (c) 2011 University of Pennsylvania. All rights reserved.
#! See https://www.rad.upenn.edu/sbia/software/license.html or COPYING file.
#!
#! Contact: SBIA Group <sbia-software at uphs.upenn.edu>
#!
#! @ingroup CMakeTools
##############################################################################

if (__BASIS_TARGETTOOLS_INCLUDED)
  return ()
else ()
  set (__BASIS_TARGETTOOLS_INCLUDED TRUE)
endif ()


# get directory of this file
#
# Note: This variable was just recently introduced in CMake, it is derived
#       here from the already earlier added variable CMAKE_CURRENT_LIST_FILE
#       to maintain compatibility with older CMake versions.
get_filename_component (CMAKE_CURRENT_LIST_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)


#! @addtogroup CMakeAPI
#! @{

# ============================================================================
# properties
# ============================================================================

# ****************************************************************************
#! @brief Replaces CMake's set_target_properties() command.
#!
#! @sa http://www.cmake.org/cmake/help/cmake-2-8-docs.html#command:set_target_properties
#!
#! @param [in] ARGN Arguments for set_target_properties().
#!
#! @returns Sets the specified properties of the given build target.

function (basis_set_target_properties)
  set (UIDS)
  list (GET ARGN 0 ARG)
  while (ARG AND NOT ARG STREQUAL "PROPERTIES")
    basis_target_uid (UID "${ARG}")
    list (APPEND UIDS "${UID}")
    list (REMOVE_AT ARGN 0)
    list (GET ARGN 0 ARG)
  endwhile ()
  if (NOT UIDS)
    message (FATAL_ERROR "basis_set_target_properties (): No targets specified")
  endif ()
  set_target_properties (${UIDS} ${ARGN})
endfunction ()

# ****************************************************************************
#! @brief Replaces CMake's get_target_property() command.
#!
#! @sa http://www.cmake.org/cmake/help/cmake-2-8-docs.html#command:get_target_property
#!
#! @param [out] VAR         Name of output variable.
#! @param [in]  TARGET_NAME Name of build target.
#! @param [in]  ARGN        Remaining arguments for get_target_property().
#!
#! @returns Sets @p VAR to the value of the requested property.

function (basis_get_target_property VAR TARGET_NAME)
  basis_target_uid (TARGET_UID "${TARGET_NAME}")
  get_target_property (VALUE "${TARGET_UID}" ${ARGN})
  set (${VAR} "${VALUE}" PARENT_SCOPE)
endfunction ()


# ****************************************************************************
#! @brief Get location of build target output file.
#!
#! This convenience function can be used to get the full path of the output
#! file generated by a given build target. It is similar to the read-only
#! @c LOCATION property of CMake targets and should be used instead of
#! reading this porperty.
#!
#! @sa http://www.cmake.org/cmake/help/cmake-2-8-docs.html#prop_tgt:LOCATION
#!
#! @param [out] VAR         Path of build target output file.
#! @param [in]  TARGET_NAME Name of build target.
#! @param [in]  ARGN        Not used.
#!
#! @returns Path of output file similar to @c LOCATION property of CMake targets.

function (basis_get_target_location VAR TARGET_NAME)
  basis_target_uid (TARGET_UID "${TARGET_NAME}")
  if (TARGET "${TARGET_UID}")
    get_target_property (BASIS_TYPE ${TARGET_UID} "BASIS_TYPE")
    if (BASIS_TYPE MATCHES "MCC|^MEX$")
      if (BASIS_TYPE MATCHES "^MCC_LIBRARY$|^MEX$")
        get_target_property (DIRECTORY "${TARGET_UID}" "LIBRARY_OUTPUT_DIRECTORY")
      else ()
        get_target_property (DIRECTORY "${TARGET_UID}" "RUNTIME_OUTPUT_DIRECTORY")
      endif ()
      get_target_property (FNAME  "${TARGET_UID}" "OUTPUT_NAME")
      get_target_property (PREFIX "${TARGET_UID}" "PREFIX")
      get_target_property (SUFFIX "${TARGET_UID}" "SUFFIX")

      set (TARGET_FILE)
      if (FNAME)
        set (TARGET_FILE "${FNAME}")
      else ()
        set (TARGET_FILE "${TARGET_NAME}")
      endif ()
      if (PREFIX)
        set (TARGET_FILE "${PREFIX}${TARGET_FILE}")
      endif ()
      if (SUFFIX)
        set (TARGET_FILE "${TARGET_FILE}${SUFFIX}")
      endif ()

      set (LOCATION "${DIRECTORY}/${TARGET_FILE}")
    else ()
      get_target_property (LOCATION "${TARGET_UID}" "LOCATION")
    endif ()
  else ()
    set (LOCATION "NOTFOUND")
  endif ()
  set ("${VAR}" "${LOCATION}" PARENT_SCOPE)
endfunction ()

# ============================================================================
# definitions
# ============================================================================

# ****************************************************************************
#! @brief Replaces CMake's add_definitions() command.
#!
#! @sa http://www.cmake.org/cmake/help/cmake-2-8-docs.html#command:add_definitions
#!
#! @param [in] ARGN Arguments for add_definition().
#!
#! @returns Adds the given definitions.

function (basis_add_definitions)
  add_definitions (${ARGN})
endfunction ()

# ****************************************************************************
#! @brief Replaces CMake's remove_definitions() command.
#!
#! @sa http://www.cmake.org/cmake/help/cmake-2-8-docs.html#command:remove_definition
#!
#! @param [in] ARGN Arguments for remove_definitions().
#!
#! @returns Removes the specified definitions.

function (basis_remove_definitions)
  remove_definitions (${ARGN})
endfunction ()

# ============================================================================
# directories
# ============================================================================

# ****************************************************************************
#! \brief Replaces CMake's include_directories() command.
#!
#! All arguments are passed on to CMake's include_directories() command.
#! Additionally, the list of include directories is stored in the cached CMake
#! variable BASIS_INCLUDE_DIRECTORIES. This variable can be used by custom
#! commands for the build process, e.g., it is used as argument for the -I
#! option of the MATLAB Compiler.
#!
#! Additionally, a list of all include directories added is cached. Hence,
#! this list is extended even across subdirectories. Directories are always
#! appended ignoring the BEFORE argument. The value of this internal cache
#! variabel is cleared by basis_project_initialize().
#!
#! @param ARGN Argument list passed on to CMake's include_directories command.
#!
#! @returns Adds the given paths to the list of include search paths and
#!          to the variables @c BASIS_INCLUDE_DIRECTORIES and
#!          @c BASIS_CACHED_INCLUDE_DIRECTORIES.

function (basis_include_directories)
  # CMake's include_directories ()
  include_directories (${ARGN})

  # parse arguments
  CMAKE_PARSE_ARGUMENTS (ARGN "AFTER;BEFORE;SYSTEM" "" "" ${ARGN})

  # current include directories
  if (BASIS_INCLUDE_DIRECTORIES)
    if (ARGN_BEFORE)
      set (
        BASIS_INCLUDE_DIRECTORIES
          "${ARGN_UNPARSED_ARGUMENTS};${BASIS_INCLUDE_DIRECTORIES}"
      )
    else ()
      set (
        BASIS_INCLUDE_DIRECTORIES
          "${BASIS_INCLUDE_DIRECTORIES};${ARGN_UNPARSED_ARGUMENTS}"
      )
    endif ()
  else ()
    set (BASIS_INCLUDE_DIRECTORIES "${ARGN_UNPARSED_ARGUMENTS}")
  endif ()

  if (BASIS_INCLUDE_DIRECTORIES)
    list (REMOVE_DUPLICATES BASIS_INCLUDE_DIRECTORIES)
  endif ()

  set (BASIS_INCLUDE_DIRECTORIES "${BASIS_INCLUDE_DIRECTORIES}" PARENT_SCOPE)

  # cached include directories
  if (BASIS_CACHED_INCLUDE_DIRECTORIES)
    set (
      BASIS_CACHED_INCLUDE_DIRECTORIES
        "${BASIS_CACHED_INCLUDE_DIRECTORIES};${ARGN_UNPARSED_ARGUMENTS}"
    )
  else ()
    set (BASIS_CACHED_INCLUDE_DIRECTORIES "${ARGN_UNPARSED_ARGUMENTS}")
  endif ()

  if (BASIS_CACHED_INCLUDE_DIRECTORIES)
    list (REMOVE_DUPLICATES BASIS_CACHED_INCLUDE_DIRECTORIES)
  endif ()

  set (
    BASIS_CACHED_INCLUDE_DIRECTORIES "${BASIS_CACHED_INCLUDE_DIRECTORIES}"
    CACHE INTERNAL "${BASIS_CACHED_INCLUDE_DIRECTORIES_DOC}" FORCE
  )
endfunction ()

# ****************************************************************************
#! @brief Replaces CMake's link_directories() command.
#!
#! @sa http://www.cmake.org/cmake/help/cmake-2-8-docs.html#command:link_directories
#!
#! @param [in] ARGN Arguments for link_directories().
#!
#! @returns Adds the given paths to the search path for link libraries and
#!          to the variable @c BASIS_LINK_DIRECTORIES.

function (basis_link_directories)
  # CMake's link_directories()
  link_directories (${ARGN})

  # current link directories
  if (BASIS_LINK_DIRECTORIES)
    set (
      BASIS_LINK_DIRECTORIES
        "${BASIS_LINK_DIRECTORIES};${ARGN}"
    )
  else ()
    set (BASIS_LINK_DIRECTORIES "${ARGN}")
  endif ()

  if (BASIS_LINK_DIRECTORIES)
    list (REMOVE_DUPLICATES BASIS_LINK_DIRECTORIES)
  endif ()

  set (BASIS_LINK_DIRECTORIES "${BASIS_LINK_DIRECTORIES}" PARENT_SCOPE)
endfunction ()

# ============================================================================
# dependencies
# ============================================================================

# ****************************************************************************
#! @brief Replaces CMake's add_dependencies() command.
#!
#! @sa http://www.cmake.org/cmake/help/cmake-2-8-docs.html#command:add_dependencies
#!
#! @param [in] ARGN Arguments for add_dependencies().
#!
#! @returns Adds the given dependencies of the specified build target.

function (basis_add_dependencies)
  set (UIDS)
  foreach (ARG ${ARGN})
    basis_target_uid (UID "${ARG}")
    list (APPEND UIDS "${UID}")
  endforeach ()
  add_dependencies (${UIDS})
endfunction ()

# ****************************************************************************
#! @brief Replaces CMake's target_link_libraries() command.
#!
#! The main reason for replacing this function is to treat libraries such as
#! MEX-files which are supposed to be compiled into a MATLAB executable added
#! by basis_add_executable() special. In this case, these libraries are added
#! to the LINK_DEPENDS property of the given MATLAB Compiler target.
#!
#! Example:
#! @code
#! basis_add_library (MyMEXFunc MEX myfunc.c)
#! basis_add_executable (MyMATLABApp main.m)
#! basis_target_link_libraries (MyMATLABApp MyMEXFunc OtherMEXFunc.mexa64)
#! @endcode
#!
#! @sa http://www.cmake.org/cmake/help/cmake-2-8-docs.html#command:target_link_libraries()
#!
#! @param [in] TARGET_NAME Name of the target.
#! @param [in] ARGN        Link libraries.
#!
#! @returns Adds link dependencies to the specified build target.
#!          For custom targets, the given libraries are added to the
#!          @c DEPENDS property of these target, in particular.

function (basis_target_link_libraries TARGET_NAME)
  basis_target_uid (TARGET_UID "${TARGET_NAME}")

  if (NOT TARGET "${TARGET_UID}")
    message (FATAL_ERROR "basis_target_link_libraries (): Unknown target ${TARGET_UID}.")
  endif ()

  get_target_property (BASIS_TYPE ${TARGET_UID} "BASIS_TYPE")

  # MATLAB Compiler or MEX target
  if (BASIS_TYPE MATCHES "MCC|MEX")
    get_target_property (DEPENDS ${TARGET_UID} "LINK_DEPENDS")

    if (NOT DEPENDS)
      set (DEPENDS)
    endif ()

    foreach (ARG ${ARGN})
      basis_target_uid (UID "${ARG}")
      if (TARGET "${UID}")
        list (APPEND DEPENDS ${UID})
      else ()
        list (APPEND DEPENDS "${ARG}")
      endif ()
    endforeach ()
 
    # pull dependencies (e.g., ITK uses this)
    if (NOT BASIS_TYPE MATCHES "MCC")
      set (DEPENDENCY_ADDED 1)
      while (DEPENDENCY_ADDED)
        set (DEPENDENCY_ADDED 0)
        foreach (LIB ${DEPENDS})
          foreach (LIB_DEPEND ${${LIB}_LIB_DEPENDS})
            if (NOT LIB_DEPEND MATCHES "^general$")
              string (REGEX REPLACE "^-l" "" LIB_DEPEND "${LIB_DEPEND}")
              list (FIND DEPENDS ${LIB_DEPEND} IDX)
              if (IDX EQUAL -1)
                list (APPEND DEPENDS ${LIB_DEPEND})
                set (DEPENDENCY_ADDED 1)
              endif ()
            endif ()
          endforeach ()
        endforeach ()
      endwhile ()
    endif ()

    set_target_properties (${TARGET_UID} PROPERTIES LINK_DEPENDS "${DEPENDS}")
  # other
  else ()
    target_link_libraries (${TARGET_UID} ${ARGN})
  endif ()
endfunction ()

# ============================================================================
# add targets
# ============================================================================

# ****************************************************************************
#! @brief Replacement for CMake's add_executable() command.
#!
#! This function adds an executable target.
#!
#! An install command for the added executable target is added by this function
#! as well. The executable will be installed as part of the component COMPONENT
#! in the directory INSTALL_RUNTIME_DIR or INSTALL_LIBEXEC_DIR if the option
#! LIBEXEC is given.
#!
#! Besides adding usual executable targets build by the set C/CXX language
#! compiler, this function inspects the list of source files given and detects
#! whether this list contains sources which need to be build using a different
#! compiler. In particular, it supports the following languages:
#!
#! <table border="0">
#!   <tr>
#!     <td>@b CXX</td>
#!     <td>The default behavior, adding an executable target build from C/C++
#!         source code. The target is added via CMake's add_executable() command.</td>
#!   </tr>
#!   <tr>
#!     <td>@b MATLAB</td>
#!     <td>Standalone application build from MATLAB sources using the
#!         MATLAB Compiler (mcc). This language option is used when the list
#!         of source files contains one or more *.m files. A custom target is
#!         added which depends on custom command(s) that build the executable.</td>
#!         <br /><br />
#!         Attention: The *.m file with the entry point/main function of the
#!                    executable has to be given before any other *.m file.
#!   </tr>
#! </table>
#!
#! @param [in] TARGET_NAME Name of the executable target.
#! @param [in] ARGN        This argument list is parsed and the following
#!                         arguments are extracted, all other arguments are passed
#!                         on to add_executable() or the respective custom
#!                         commands used to build the executable.
#! @par
#! <table border="0">
#!   <tr>
#!     <td style="white-space:nowrap; vertical-align:top; padding-right:1em">
#!         @b COMPONENT name</td>
#!     <td>Name of the component. Default: @c BASIS_RUNTIME_COMPONENT.</td>
#!   </tr>
#!   <tr>
#!     <td style="white-space:nowrap; vertical-align:top; padding-right:1em">
#!         @b LANGUAGE lang</td>
#!     <td>Source code language. By default determined from the extensions of
#!         of the given source files, where CXX is assumed if no other
#!         language is detected.</td>
#!   </tr>
#!   <tr>
#!     <td style="white-space:nowrap; vertical-align:top; padding-right:1em">
#!         @b LIBEXEC</td>
#!     <td>Specifies that the built executable is an auxiliary executable
#!         which is only called by other executable.</td>
#!   </tr>
#!   <tr>
#!     <td style="white-space:nowrap; vertical-align:top; padding-right:1em">
#!         @b TEST</td>
#!     <td>Specifies that the built executable is a test executable used
#!         with basis_add_test(). If also @p LIBEXEC is given, it is ignored.</td>
#!   </tr>
#! </table>
#!
#! @returns Adds an executable build target. In case of a MATLAB Compiler
#!          target, the function basis_add_custom_finalize() has to be
#!          invoked to actually add the custom target that builds the executable.

function (basis_add_executable TARGET_NAME)
  basis_check_target_name (${TARGET_NAME})
  basis_target_uid (TARGET_UID "${TARGET_NAME}")

  # parse arguments
  CMAKE_PARSE_ARGUMENTS (ARGN "LIBEXEC;TEST" "COMPONENT;LANGUAGE" "" ${ARGN})

  # if no component is specified, use default
  if (NOT ARGN_COMPONENT)
    set (ARGN_COMPONENT "${BASIS_RUNTIME_COMPONENT}")
  endif ()
  if (NOT ARGN_COMPONENT)
    set (ARGN_COMPONENT "Unspecified")
  endif ()

  if (ARGN_TEST)
    set (ARGN_LIBEXEC 0)
  endif ()

  # if the language is not explicitly selected, determine it from the
  # extensions of the source files
  if (NOT ARGN_LANGUAGE)
    set (ARGN_LANGUAGE "CXX")
    foreach (ARG ${ARGN})
      if (ARG MATCHES "\\.m$")
        set (ARGN_LANGUAGE "MATLAB")
      endif ()
    endforeach ()
  endif ()

  # --------------------------------------------------------------------------
  # MATLAB Compiler
  # --------------------------------------------------------------------------

  if (ARGN_LANGUAGE STREQUAL "MATLAB")

    if (ARGN_TEST)
      set (EXECOPT "TEST")
    elseif (ARGN_LIBEXEC)
      set (EXECOPT "LIBEXEC")
    else ()
      set (EXECOPT "")
    endif ()

    basis_add_mcc_target (
      ${TARGET_NAME}
      TYPE      "EXECUTABLE"
      COMPONENT "${ARGN_COMPONENT}"
      ${EXECOPT}
      ${ARGN_UNPARSED_ARGUMENTS}
    )

  # --------------------------------------------------------------------------
  # other (just wrap add_executable () by default)
  # --------------------------------------------------------------------------

  else ()

    message (STATUS "Adding executable ${TARGET_UID}...")

    # add executable target
    add_executable (${TARGET_UID} ${ARGN_UNPARSED_ARGUMENTS})

    if (ARGN_TEST)
      set (TYPE "TEST")
    elseif (ARGN_LIBEXEC)
      set (TYPE "LIBEXEC")
    else ()
      set (TYPE "EXEC")
    endif ()

    set_target_properties (
      ${TARGET_UID}
      PROPERTIES
        BASIS_TYPE "${TYPE}"
    )

    if (ARGN_LIBEXEC)
      set_target_properties (
        ${TARGET_UID}
        PROPERTIES
          COMPILE_DEFINITIONS "LIBEXEC"
      )
    endif ()

    # target version information
    # Note: On UNIX-based systems this only creates annoying files with
    #       the version string as suffix and two symbolic links.
    if (WIN32)
      set_target_properties (
        ${TARGET_UID}
        PROPERTIES
          VERSION   ${PROJECT_VERSION}
          SOVERSION ${PROJECT_SOVERSION}
      )
    endif ()

    # install executable
    if (ARGN_TEST)
      # TODO install (selected?) tests
    else ()
      if (ARGN_LIBEXEC)
        set (INSTALL_DIR "${INSTALL_LIBEXEC_DIR}")
      else ()
        set (INSTALL_DIR "${INSTALL_RUNTIME_DIR}")
      endif ()

      install (
        TARGETS     ${TARGET_UID}
        EXPORT      "${PROJECT_NAME}"
        DESTINATION "${INSTALL_DIR}"
        COMPONENT   "${ARGN_COMPONENT}"
      )

      set (
        BASIS_CACHED_EXPORTS "${BASIS_CACHED_EXPORTS};${TARGET_UID}"
        CACHE INTERNAL "${BASIS_CACHED_EXPORTS_DOC}" FORCE
      )

      set_target_properties (
        ${TARGET_UID}
        PROPERTIES
          RUNTIME_INSTALL_DIRECTORY "${INSTALL_DIR}"
      )
    endif ()

    # add target to list of targets
    set (
      BASIS_TARGETS "${BASIS_TARGETS};${TARGET_UID}"
      CACHE INTERNAL "${BASIS_TARGETS_DOC}" FORCE
    )

    message (STATUS "Adding executable ${TARGET_UID}... - done")

  endif ()
endfunction ()

# ****************************************************************************
#! @brief Replaces CMake's add_library() command.
#!
#! This function adds a library target.
#!
#! An install command for the added library target is added by this function
#! as well. The runtime library will be installed as part of the component
#! RUNTIME_COMPONENT in the directory INSTALL_LIBRARY_DIR on UNIX systems
#! and INSTALL_RUNTIME_DIR on Windows. Static/import libraries will be installed
#! as part of the LIBRARY_COMPONENT in the directory INSTALL_ARCHIVE_DIR.
#!
#! Example:
#! @code
#! basis_add_library (MyLib1 STATIC mylib.cc)
#! basis_add_library (MyLib2 STATIC mylib.cc COMPONENT dev)
#!
#! basis_add_library (
#!   MyLib3 SHARED mylib.cc
#!   RUNTIME_COMPONENT bin
#!   LIBRARY_COMPONENT dev
#! )
#! @endcode
#!
#! @param [in] TARGET_NAME Name of the library target.
#! @param [in] ARGN        Arguments passed to add_library() (excluding target name).
#!                         This argument list is parsed and the following
#!                         arguments are extracted, all other arguments are passed
#!                         on to add_library().
#! @par
#! <table border="0">
#!   <tr>
#!     <td style="white-space:nowrap; vertical-align:top; padding-right:1em">
#!         @b COMPONENT name</td>
#!     <td>Name of the component. Default: @c BASIS_LIBRARY_COMPONENT.</td>
#!   </tr>
#!   <tr>
#!     <td style="white-space:nowrap; vertical-align:top; padding-right:1em">
#!         @b RUNTIME_COMPONENT name</td>
#!     <td>Name of runtime component. Default: @c COMPONENT if specified or
#!         @c BASIS_RUNTIME_COMPONENT, otherwise.</td>
#!   </tr>
#!   <tr>
#!     <td style="white-space:nowrap; vertical-align:top; padding-right:1em">
#!         @b LIBRARY_COMPONENT name</td>
#!     <td>Name of library component. Default: @c COMPONENT if specified or
#!         @c BASIS_LIBRARY_COMPONENT, otherwise.</td>
#!   </tr>
#!   <tr>
#!     <td style="white-space:nowrap; vertical-align:top; padding-right:1em">
#!         <b>STATIC</b>|<b>SHARED</b>|<b>MODULE</b>|<b>MEX</b>|<b>LIBMEX</b></td>
#!     <td>Type of the library.</td>
#!   </tr>
#!   <tr>
#!     <td style="white-space:nowrap; vertical-align:top; padding-right:1em">
#!         @b EXTERNAL</td>
#!     <td>Whether the library target is an external library, i.e., the project
#!         version does not apply.</td>
#!   </tr>
#! </table>
#!
#! @returns Adds a library build target. In case of a MATLAB Complier target
#!          or a MEX script target, basis_add_custom_finalize() has to be invoked
#!          to actually add the custom target that builds the library.

function (basis_add_library TARGET_NAME)
  basis_check_target_name (${TARGET_NAME})
  basis_target_uid (TARGET_UID "${TARGET_NAME}")

  # parse arguments
  CMAKE_PARSE_ARGUMENTS (
    ARGN
      "STATIC;SHARED;MODULE;MEX;LIBMEX;EXTERNAL"
      "COMPONENT;LIBRARY_COMPONENT;RUNTIME_COMPONENT;LANGUAGE"
      ""
    ${ARGN}
  )

  if (NOT ARGN_LIBRARY_COMPONENT AND ARGN_COMPONENT)
    set (ARGN_LIBRARY_COMPONENT "${ARGN_COMPONENT}")
  endif ()
  if (NOT ARGN_RUNTIME_COMPONENT AND ARGN_COMPONENT)
    set (ARGN_RUNTIME_COMPONENT "${ARGN_COMPONENT}")
  endif ()

  if (NOT ARGN_COMPONENT)
    set (ARGN_COMPONENT "${BASIS_LIBRARY_COMPONENT}")
  endif ()
  if (NOT ARGN_COMPONENT)
    set (ARGN_COMPONENT "Unspecified")
  endif ()

  if (NOT ARGN_LIBRARY_COMPONENT)
    set (ARGN_LIBRARY_COMPONENT "${BASIS_LIBRARY_COMPONENT}")
  endif ()
  if (NOT ARGN_LIBRARY_COMPONENT)
    set (ARGN_LIBRARY_COMPONENT "Unspecified")
  endif ()

  if (NOT ARGN_RUNTIME_COMPONENT)
    set (ARGN_RUNTIME_COMPONENT "${BASIS_RUNTIME_COMPONENT}")
  endif ()
  if (NOT ARGN_RUNTIME_COMPONENT)
    set (ARGN_RUNTIME_COMPONENT "Unspecified")
  endif ()

  # if the language is not explicitly selected, determine it from the
  # extensions of the source files
  if (NOT ARGN_LANGUAGE)
    foreach (ARG ${ARGN})
      if (ARG MATCHES "\\.m$")
        set (ARGN_LANGUAGE "MATLAB")
      endif ()
    endforeach ()
  endif ()

  # by default, consider source files as CXX language
  # (i.e., defaults to behavior of CMake's add_library ())
  if (NOT ARGN_LANGUAGE)
    set (ARGN_LANGUAGE "CXX")
  endif ()

  # status message including parsing of library type
  if (ARGN_LANGUAGE STREQUAL "MATLAB")
    message (STATUS "Adding MATLAB library ${TARGET_UID}...")
    if (NOT ARGN_SHARED OR ARGN_STATIC OR ARGN_MODULE OR ARGN_MEX)
      message (FATAL_ERROR "Invalid type for MATLAB library target ${TARGET_UID}. Only SHARED allowed.")
    endif ()
    set (ARGN_TYPE "SHARED")
  else ()
    if (NOT ARGN_SHARED AND NOT ARGN_STATIC AND NOT ARGN_MODULE AND NOT ARGN_MEX)
      if (BUILD_SHARED_LIBS)
        set (ARGN_SHARED 1)
      else ()
        set (ARGN_STATIC 0)
      endif ()
    endif ()

    if (ARGN_STATIC)
      message (STATUS "Adding static library ${TARGET_UID}...")
      if (ARGN_TYPE)
        message (FATAL_ERROR "More than one library type specified for target ${TARGET_UID}.")
      endif ()
      set (ARGN_TYPE "STATIC")
    endif ()
    if (ARGN_SHARED)
      message (STATUS "Adding shared library ${TARGET_UID}...")
      if (ARGN_TYPE)
        message (FATAL_ERROR "More than one library type specified for target ${TARGET_UID}.")
      endif ()
      set (ARGN_TYPE "SHARED")
    endif ()
    if (ARGN_MODULE)
      message (STATUS "Adding shared module ${TARGET_UID}...")
      if (ARGN_TYPE)
        message (FATAL_ERROR "More than one library type specified for target ${TARGET_UID}.")
      endif ()
      set (ARGN_TYPE "MODULE")
    endif ()
    if (ARGN_MEX)
      message (STATUS "Adding MEX-file ${TARGET_UID}...")
      if (ARGN_TYPE)
        message (FATAL_ERROR "More than one library type specified for target ${TARGET_UID}.")
      endif ()
      set (ARGN_TYPE "MEX")
    endif ()
    if (ARGN_LIBMEX)
      message (STATUS "Adding MEX-file (library) ${TARGET_UID}...")
      if (ARGN_TYPE)
        message (FATAL_ERROR "More than one library type specified for target ${TARGET_UID}.")
      endif ()
      set (ARGN_TYPE "LIBMEX")
    endif ()
  endif ()

  # --------------------------------------------------------------------------
  # MATLAB Compiler
  # --------------------------------------------------------------------------

  if (ARGN_LANGUAGE STREQUAL "MATLAB")

    basis_add_mcc_target (
      ${TARGET_NAME}
      TYPE              "LIBRARY"
      RUNTIME_COMPONENT "${ARGN_RUNTIME_COMPONENT}"
      LIBRARY_COMPONENT "${ARGN_LIBRARY_COMPONENT}"
      ${ARGN_UNPARSED_ARGUMENTS}
    )

  # --------------------------------------------------------------------------
  # MEX
  # --------------------------------------------------------------------------

  elseif (ARGN_TYPE STREQUAL "MEX")
 
    basis_add_mex_target (
      ${TARGET_NAME}
      COMPONENT ${ARGN_LIBRARY_COMPONENT}
      ${ARGN_UNPARSED_ARGUMENTS}
    )

  # --------------------------------------------------------------------------
  # C/C++
  # --------------------------------------------------------------------------

  else ()

    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # MEX (build simply as shared library)
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    if (ARGN_TYPE STREQUAL "LIBMEX")

      # MATLAB external library found ?
      if (NOT MATLAB_FOUND)
        message (FATAL_ERROR "MATLAB package not found or not searched for."
                             " It is required to build target ${TARGET_UID}.")
      endif ()

      # determine extension of MEX-files for this architecture
      basis_mexext ()

      if (NOT MEX_EXT)
        message (FATAL_ERROR "Failed to determine extension of MEX-files. It is required to build target ${TARGET_UID}."
                             "Set BASIS_CMD_MEXEXT or MEX_EXT and try again.")
      endif ()

      # add library target
      add_library (${TARGET_UID} SHARED ${ARGN_UNPARSED_ARGUMENTS})

      set_target_properties (
        ${TARGET_UID}
        PROPERTIES
          BASIS_TYPE "MEX_FILE"
      )

      target_link_libraries (${TARGET_UID} ${MATLAB_LIBRARIES})

      # compiler flags and definitions specific to MEX-file build
      set (
        MEX_DEFINITIONS
          "_FILE_OFFSET_BITS=64"
          #"ARGCHECK"     # corresponds to MEX option -argcheck            ==> user may add via add_definitions ()
          #"MX_COMPAT_32" # corresponds to MEX option -compatibleArrayDims ==> user may add via add_definitions ()
          "MATLAB_MEX_FILE"
      )

      set (MEX_COMPILE_FLAGS)
      set (MEX_LINK_FLAGS)

      if (CMAKE_COMPILER_IS_GNUCC OR CMAKE_COMPILER_ISGNUCXX)
        list (APPEND MEX_DEFINITIONS "_GNU_SOURCE")
        if (HAVE_PTHREAD)
          set (MEX_COMPILE_FLAGS "${MEX_COMPILE_FLAGS} -pthread")
        endif ()
        set (MEX_COMPILE_FLAGS "${MEX_COMPILE_FLAGS} -fPIC -fexceptions -fno-omit-frame-pointer")
        set (MEX_LINK_FLAGS "${MEX_LINK_FLAGS} -lstdc++")
      else ()
        message (WARNING "Build of MEX-files with non-GNU compiler is not supported")
      endif ()

      set_target_properties (
        ${TARGET_UID}
        PROPERTIES
          PREFIX              ""
          SUFFIX              ".${MEX_EXT}"
          COMPILE_DEFINITIONS "${MEX_DEFINITIONS}"
          COMPILE_FLAGS       "${MEX_COMPILE_FLAGS}"
          LINK_FLAGS          "${MEX_LINK_FLAGS}"
      )

    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # other libraries
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    else ()

      add_library (${TARGET_UID} ${ARGN_TYPE} ${ARGN_UNPARSED_ARGUMENTS})

      set_target_properties (
        ${TARGET_UID}
        PROPERTIES
          BASIS_TYPE "LIBRARY"
      )

    endif ()

    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # common
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    # target version information
    # Note:      On UNIX-based systems this only creates annoying files with the
    #            version string as suffix.
    # Attention: MEX-files may NEVER have a suffix after the MEX extension!
    #            Otherwise, the MATLAB Compiler when using the symbolic link
    #            without this suffix will create code that fails on runtime
    #            with an .auth file missing error.
    if (NOT ARGN_EXTERNAL AND WIN32)
      set_target_properties (
        ${TARGET_NAME}
        PROPERTIES
          VERSION   "${PROJECT_VERSION}"
          SOVERSION "${PROJECT_SOVERSION}"
      )
    endif ()

    # install library
    install (
      TARGETS ${TARGET_UID}
      EXPORT  "${PROJECT_NAME}"
      RUNTIME
        DESTINATION "${INSTALL_RUNTIME_DIR}"
        COMPONENT   "${ARGN_RUNTIME_COMPONENT}"
      LIBRARY
        DESTINATION "${INSTALL_LIBRARY_DIR}"
        COMPONENT   "${ARGN_LIBRARY_COMPONENT}"
      ARCHIVE
        DESTINATION "${INSTALL_ARCHIVE_DIR}"
        COMPONENT   "${ARGN_LIBRARY_COMPONENT}"
    )

    set (
      BASIS_CACHED_EXPORTS "${BASIS_CACHED_EXPORTS};${TARGET_UID}"
      CACHE INTERNAL "${BASIS_CACHED_EXPORTS_DOC}" FORCE
    )

    # add target to list of targets
    set (
      BASIS_TARGETS "${BASIS_TARGETS};${TARGET_UID}"
      CACHE INTERNAL "${BASIS_TARGETS_DOC}" FORCE
    )

  endif ()

  # done
  if (ARGN_LANGUAGE STREQUAL "MATLAB")
    message (STATUS "Adding MATLAB library ${TARGET_UID}... - done")
  else ()
    if (ARGN_STATIC)
      message (STATUS "Adding static library ${TARGET_UID}... - done")
    elseif (ARGN_SHARED)
      message (STATUS "Adding shared library ${TARGET_UID}... - done")
    elseif (ARGN_MODULE)
      message (STATUS "Adding shared module ${TARGET_UID}... - done")
    elseif (ARGN_MEX)
      message (STATUS "Adding MEX-file ${TARGET_UID}... - done")
    endif ()
  endif ()
endfunction ()

# ****************************************************************************
#! @brief Add script target.
#!
#! This function adds a script target to the project, where during the build
#! step the script is configured via configure_file() and copied to the
#! directory specified by OUTPUT_DIRECTORY. During installation, the script
#! built for the install tree is copied to the specified DESTINATION.
#!
#! If the script name ends in ".in", the ".in" suffix is removed from the
#! output name. Further, all occurrences of ".in." anywhere within the script
#! name are removed as well. The extension of the script such as .sh or .py is
#! removed from the output filename if the project is build on UNIX systems
#! and the script file contains a sha-bang directive, i.e., the first two
#! characters on the first line are "#!" followed by the path to the script
#! language interpreter.
#!
#! Example:
#! @code
#! basis_add_script (MyShellScript.sh.in)
#! basis_add_script (AnotherShellScript.in.sh)
#! basis_add_script (Script SCRIPT Script1.sh)
#! @endcode
#!
#! Certain CMake variables within the script are replaced during the configure step.
#! These variables and their values are given by a so-called script config(uration)
#! file. The specified script configuration file is loaded during the build of
#! the script prior to the configure_file() command. As paths may be different
#! for scripts that are used directly from the build tree and scripts that are
#! copied into the install tree, the variable BUILD_INSTALL_SCRIPT is 1 when the
#! script is build for the install tree and 0 otherwise. This variable can be
#! used within the script configuration file to set the value of the CMake
#! variables used within the script differently for either case.
#!
#! Example:
#! @code
#! basis_add_script (Script1 SCRIPT Script1.sh CONFIG Script1Config.cmake)
#! @endcode
#!
#! Script1Config.cmake
#! @code
#! basis_set_script_path (ETC_DIR "@PROJECT_ETC_DIR@" "@INSTALL_ETC_DIR@")
#! @endcode
#!
#! See documentation of basis_set_script_path_definition() and ScriptConfig.cmake
#! file in @c BASIS_MODULE_PATH for details.
#!
#! Note that this function only adds a custom target and stores all information
#! required to setup the actual custom build command as properties of this target.
#! The custom build command itself is added by basis_add_script_finalize(), which
#! is supposed to be called once at the end of the root CMakeLists.txt file of the
#! (super-)project. This way properties such as the OUTPUT_NAME can still be modified
#! after adding the script target.
#!
#! If a custom script configuration file is used, the variable
#! \@BASIS_SCRIPT_CONFIG\@ can be used within this custom script configuration file
#! to include the default configuration of the BASIS_SCRIPT_CONFIG_FILE.
#!
#! @sa basis_add_script_finalize()
#!
#! @param [in] TARGET_NAME Name of the target. Alternatively, the script file
#!                         path relative to the current source directory can be
#!                         given here. In this case, the basename of the script
#!                         file is used as target name and the SCRIPT option may
#!                         not be used.
#! @param [in] ARGN        This argument list is parsed and the following
#!                         arguments are extracted:
#! @par
#! <table border="0">
#!   <tr>
#!      <td style="white-space:nowrap; vertical-align:top; padding-right:1em">
#!          @b SCRIPT file</td>
#!      <td>Script file path relative to current source directory.</td>
#!   </tr>
#!   <tr>
#!      <td style="white-space:nowrap; vertical-align:top; padding-right:1em">
#!          @b OUTPUT_DIRECTORY dir</td>
#!      <td>The output directory for the configured script in the
#!          build tree. Default: @c CMAKE_RUNTIME_OUTPUT_DIRECTORY.</td>
#!   </tr>
#!   <tr>
#!      <td style="white-space:nowrap; vertical-align:top; padding-right:1em">
#!          @b DESTINATION dir</td>
#!      <td>The installation directory relative to @c INSTALL_PREFIX.
#!          Default: @c INSTALL_RUNTIME_DIR or @c INSTALL_LIBEXEC_DIR if
#!                   the @p LIBEXEC option is given.</td>
#!   </tr>
#!   <tr>
#!      <td style="white-space:nowrap; vertical-align:top; padding-right:1em">
#!          @b COMPONENT name</td>
#!      <td>Name of the component. Default: @c BASIS_RUNTIME_COMPONENT.</td>
#!   </tr>
#!   <tr>
#!      <td style="white-space:nowrap; vertical-align:top; padding-right:1em">
#!          @b CONFIG file</td>
#!      <td>Script configuration file. Default: @c DEFAULT_SCRIPT_CONFIG_FILE
#!          if this variable is set. If "NONE", "None", or "none" is given,
#!          the script is copied only. Otherwise, a script configuration
#!          consisting of the single line "\@BASIS_SCRIPT_CONFIG\@" is used.</td>
#!   </tr>
#!   <tr>
#!      <td style="white-space:nowrap; vertical-align:top; padding-right:1em">
#!          @b LIBEXEC</td>
#!      <td>Specifies that the script is an auxiliary executable called
#!          by other executables only.</td>
#!   </tr>
#!   <tr>
#!      <td style="white-space:nowrap; vertical-align:top; padding-right:1em">
#!          @b NOEXEC</td>
#!      <td>Specifies that the script cannot be "executed" directly,
#!          but always requires some kind of interpreter. Note that
#!          with this option, the meaning of "script" can be even more
#!          general. Any text file, which is processed by a program
#!          to perform certain tasks, i.e., a configuration file
#!          can be considered as "script" in this sense.
#!          If the option @p LIBEXEC is given, this option is ignored.</td>
#!   </tr>
#!   <tr>
#!      <td style="white-space:nowrap; vertical-align:top; padding-right:1em">
#!          @b KEEPEXT</td>
#!      <td>If this option is given, it forces this function to keep
#!          the scripts file name extension even if a sha-bang
#!          directive is given on Unix-based systems.</td>
#!   </tr>
#!   <tr>
#!      <td style="white-space:nowrap; vertical-align:top; padding-right:1em">
#!          @b MODULE</td>
#!      <td>Specifies that the script is a module file which is included by
#!          other scripts. In particular, this is an alias for @p NOEXEC and
#!          @p KEEPEXT and can be used, for example, for Python modules
#!          that are to be imported by other Python scripts.</td>
#!   </tr>
#! </table>
#!
#! @returns Adds custom build target @p TARGET_NAME. In order to add the
#!          custom target that actually builds the script file,
#!          basis_add_custom_finalize() has to be invoked.

function (basis_add_script TARGET_NAME)
  # parse arguments
  CMAKE_PARSE_ARGUMENTS (
    ARGN
      "LIBEXEC;NOEXEC;KEEPEXT;MODULE"
      "SCRIPT;CONFIG;COMPONENT;OUTPUT_DIRECTORY;DESTINATION"
      ""
    ${ARGN}
  )

  if (NOT ARGN_COMPONENT)
    set (ARGN_COMPONENT "${BASIS_RUNTIME_COMPONENT}")
  endif ()
  if (NOT ARGN_COMPONENT)
    set (ARGN_COMPONENT "Unspecified")
  endif ()

  if (NOT ARGN_OUTPUT_DIRECTORY)
    set (ARGN_OUTPUT_DIRECTORY "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")
  endif ()
  if (NOT IS_ABSOLUTE "${ARGN_OUTPUT_DIRECTORY}")
    set (ARGN_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/${ARGN_OUTPUT_DIRECTORY}")
  endif ()
  if (NOT ARGN_DESTINATION)
    if (ARGN_LIBEXEC)
      set (ARGN_DESTINATION "${INSTALL_LIBEXEC_DIR}")
    else ()
      set (ARGN_DESTINATION "${INSTALL_RUNTIME_DIR}")
    endif ()
  endif ()

  if (IS_ABSOLUTE "${ARGN_DESTINATION}")
    message (FATAL_ERROR "basis_add_script (${TARGET_NAME}: Destination must be a relative path")
  endif ()

  if (NOT ARGN_CONFIG AND DEFAULT_SCRIPT_CONFIG_FILE)
    set (ARGN_CONFIG "${DEFAULT_SCRIPT_CONFIG_FILE}")
  endif ()

  if (ARGN_MODULE)
    set (ARGN_KEEPEXT 1)
    set (ARGN_NOEXEC  1)
  endif ()

  if (ARGN_LIBEXEC)
    set (ARGN_NOEXEC 0)
  endif ()

  if (ARGN_UNPARSED_ARGUMENTS)
    message (FATAL_ERROR "Unknown arguments given for basis_add_script (${TARGET_NAME}): ${ARGN_UNPARSED_ARGUMENTS}")
  endif ()

  if (NOT ARGN_SCRIPT)
    set (ARGN_SCRIPT "${TARGET_NAME}")
 
    # use file basename as target name
    get_filename_component (TARGET_NAME "${TARGET_NAME}" NAME_WE)

    # remove ".in" from target name
    string (REGEX REPLACE "\\.in$"          ""    TARGET_NAME "${TARGET_NAME}")
    string (REGEX REPLACE "\\.in\(\\..*\)$" "\\1" TARGET_NAME "${TARGET_NAME}")
  endif ()

  # check target name
  basis_check_target_name ("${TARGET_NAME}")
  basis_target_uid (TARGET_UID "${TARGET_NAME}")

  message (STATUS "Adding script ${TARGET_UID}...")

  # make script file path absolute
  if (NOT IS_ABSOLUTE "${ARGN_SCRIPT}")
    set (ARGN_SCRIPT "${CMAKE_CURRENT_SOURCE_DIR}/${ARGN_SCRIPT}")
  endif ()

  if (NOT EXISTS "${ARGN_SCRIPT}")
    if (EXISTS "${ARGN_SCRIPT}.in")
      set (ARGN_SCRIPT "${ARGN_SCRIPT}.in")
    else ()
      get_filename_component (DIR    "${ARGN_SCRIPT}" PATH)
      get_filename_component (FNAME  "${ARGN_SCRIPT}" NAME_WE)
      get_filename_component (SUFFIX "${ARGN_SCRIPT}" EXT)
      if (EXISTS "${DIR}/${FNAME}.in${SUFFIX}")
        set (ARGN_SCRIPT "${DIR}/${FNAME}.in${SUFFIX}")
      endif ()
    endif ()
  endif ()

  if (NOT EXISTS "${ARGN_SCRIPT}")
    message (FATAL_ERROR "Missing script ${ARGN_SCRIPT}!")
  endif ()

  # target output name
  get_filename_component (OUTPUT_NAME "${ARGN_SCRIPT}" NAME)

  # remove ".in" from output name
  string (REGEX REPLACE "\\.in$"          ""    OUTPUT_NAME "${OUTPUT_NAME}")
  string (REGEX REPLACE "\\.in\(\\..*\)$" "\\1" OUTPUT_NAME "${OUTPUT_NAME}")

  # remove extension from script name (if UNIX system and sha-bang directive exists)
  if (NOT ARGN_KEEPEXT AND UNIX)
    file (STRINGS "${ARGN_SCRIPT}" SHABANG LIMIT_COUNT 2 LIMIT_INPUT 2)
    if (SHABANG STREQUAL "#!")
      get_filename_component (OUTPUT_NAME "${OUTPUT_NAME}" NAME_WE)
    endif ()
  endif ()

  # auxiliary executable?
  if (ARGN_LIBEXEC)
    set (TYPE "LIBSCRIPT")
  else ()
    set (TYPE "SCRIPT")
  endif ()
  if (ARGN_NOEXEC)
    set (TYPE "NOEXEC_${TYPE}")
  endif ()

  # script configuration
  set (INSTALL_DIR "${ARGN_DESTINATION}")
  set (SCRIPT_CONFIG)

  if (NOT ARGN_CONFIG MATCHES "^NONE$|^None$|^none$")
    if (BASIS_SCRIPT_CONFIG_FILE)
      file (READ "${BASIS_SCRIPT_CONFIG_FILE}" BASIS_SCRIPT_CONFIG)
    else ()
      set (BASIS_SCRIPT_CONFIG)
    endif ()

    if (ARGN_CONFIG)
      if (NOT EXISTS "${ARGN_CONFIG}")
        message (FATAL_ERROR "Script configuration file \"${ARGN_CONFIG}\" does not exist. It is required to build the script ${TARGET_UID}.")
      endif ()
      file (READ "${ARGN_CONFIG}" SCRIPT_CONFIG)
    else ()
      set (SCRIPT_CONFIG "@BASIS_SCRIPT_CONFIG@")
    endif ()
    while (SCRIPT_CONFIG MATCHES "@[a-zA-Z0-9_-]+@")
      string (CONFIGURE "${SCRIPT_CONFIG}" SCRIPT_CONFIG @ONLY)
    endwhile ()
    set (BASIS_SCRIPT_CONFIG)
  endif ()

  # add custom target
  add_custom_target (${TARGET_UID} ALL SOURCES ${ARGN_SCRIPT})

  # set target properties required by basis_add_script_finalize ()
  set_target_properties (
    ${TARGET_UID}
    PROPERTIES
      TYPE                      "EXECUTABLE"
      BASIS_TYPE                "${TYPE}"
      SOURCE_DIRECTORY          "${CMAKE_CURRENT_SOURCE_DIR}"
      BINARY_DIRECTORY          "${CMAKE_CURRENT_BINARY_DIR}"
      RUNTIME_OUTPUT_DIRECTORY  "${ARGN_OUTPUT_DIRECTORY}"
      RUNTIME_INSTALL_DIRECTORY "${ARGN_DESTINATION}"
      OUTPUT_NAME               "${OUTPUT_NAME}"
      COMPILE_DEFINITIONS       "${SCRIPT_CONFIG}"
      RUNTIME_COMPONENT         "${ARGN_COMPONENT}"
  )

  # add target to list of targets
  set (
    BASIS_TARGETS "${BASIS_TARGETS};${TARGET_UID}"
    CACHE INTERNAL "${BASIS_TARGETS_DOC}" FORCE
  )

  message (STATUS "Adding script ${TARGET_UID}... - done")
endfunction ()

# ****************************************************************************
#! @brief Finalize addition of script.
#!
#! This function uses the properties of the custom script target added by
#! basis_add_script() to create the custom build command and adds this build
#! command as dependency of this added target.
#!
#! @sa basis_add_script()
#! @sa basis_add_custom_finalize()
#!
#! @param [in] TARGET_UID "Global" target name. If this function is used
#!                        within the same project as basis_add_script(),
#!                        the "local" target name may be given alternatively.
#! @param [in] ARGN       Not used.
#!
#! @returns Adds custom target(s) to actually build the script target
#!          @p TARGET_UID added by basis_add_script().
#!
#! @ingroup CMakeUtilities

function (basis_add_script_finalize TARGET_UID)
  # if used within (sub-)project itself, allow user to specify "local" target name
  basis_target_uid (TARGET_UID "${TARGET_UID}")

  # already finalized before ?
  if (TARGET "${TARGET_UID}+")
    return ()
  endif ()

  # does this target exist ?
  if (NOT TARGET "${TARGET_UID}")
    message (FATAL_ERROR "Unknown target ${TARGET_UID}.")
    return ()
  endif ()

  message (STATUS "Adding build command for script ${TARGET_UID}...")

  # get target properties
  basis_target_name (TARGET_NAME ${TARGET_UID})

  set (
    PROPERTIES
      "BASIS_TYPE"
      "SOURCE_DIRECTORY"
      "BINARY_DIRECTORY"
      "RUNTIME_OUTPUT_DIRECTORY"
      "RUNTIME_INSTALL_DIRECTORY"
      "PREFIX"
      "OUTPUT_NAME"
      "SUFFIX"
      "VERSION"
      "SOVERSION"
      "SOURCES"
      "COMPILE_DEFINITIONS"
      "RUNTIME_COMPONENT"
  )

  foreach (PROPERTY ${PROPERTIES})
    get_target_property (${PROPERTY} ${TARGET_UID} ${PROPERTY})
  endforeach ()

  # check target type
  if (NOT BASIS_TYPE MATCHES "^SCRIPT$|^NOEXEC_SCRIPT$|^LIBSCRIPT$|^NOEXEC_LIBSCRIPT$")
    message (FATAL_ERROR "Target ${TARGET_UID} has invalid BASIS_TYPE: ${BASIS_TYPE}")
  endif ()

  # build directory (note that CMake returns basename of build directory as first element of SOURCES list)
  list (GET SOURCES 0 BUILD_DIR)
  set (BUILD_DIR "${BUILD_DIR}.dir")

  # extract script file from SOURCES
  list (GET SOURCES 1 SCRIPT_FILE)

  # output name
  if (NOT OUTPUT_NAME)
    set (OUTPUT_NAME "${TARGET_NAME}")
  endif ()

  # create build script
  set (BUILD_DIR    "${BINARY_DIRECTORY}/CMakeFiles/${TARGET_UID}.dir")
  set (BUILD_SCRIPT "${BUILD_DIR}/build.cmake")
  set (OUTPUT_FILE  "${RUNTIME_OUTPUT_DIRECTORY}/${OUTPUT_NAME}")
  set (INSTALL_FILE "${SCRIPT_FILE}")
  set (OUTPUT_FILES "${OUTPUT_FILE}")

  set (BUILD_COMMANDS "# DO NOT edit. This file is automatically generated by BASIS.\n\n")

  if (COMPILE_DEFINITIONS)
    basis_set_script_path_definition (FUNCTIONS)
    string (CONFIGURE "${FUNCTIONS}" FUNCTIONS @ONLY)

    set (INSTALL_FILE "${BUILD_DIR}/${OUTPUT_NAME}")
    set (OUTPUT_FILES "${OUTPUT_FILE};${INSTALL_FILE}")

    string (REPLACE "\r" "" COMPILE_DEFINITIONS "${COMPILE_DEFINITIONS}")

    set (BUILD_COMMANDS "${BUILD_COMMANDS}${FUNCTIONS}\n\n")
    set (BUILD_COMMANDS "${BUILD_COMMANDS}set (BUILD_INSTALL_SCRIPT 0)\n")
    set (BUILD_COMMANDS "${BUILD_COMMANDS}set (SCRIPT_DIR \"${RUNTIME_OUTPUT_DIRECTORY}\")\n")
    set (BUILD_COMMANDS "${BUILD_COMMANDS}${COMPILE_DEFINITIONS}\n")
    set (BUILD_COMMANDS "${BUILD_COMMANDS}configure_file (\"${SCRIPT_FILE}\" \"${OUTPUT_FILE}\" @ONLY)\n")
    if (NOT BASIS_TYPE MATCHES "NOEXEC")
    set (BUILD_COMMANDS "${BUILD_COMMANDS}\nif (UNIX)\n")
    set (BUILD_COMMANDS "${BUILD_COMMANDS}  execute_process (COMMAND chmod +x \"${OUTPUT_FILE}\")\n")
    set (BUILD_COMMANDS "${BUILD_COMMANDS}endif ()\n")
    endif ()
    set (BUILD_COMMANDS "${BUILD_COMMANDS}\nset (BUILD_INSTALL_SCRIPT 1)\n")
    set (BUILD_COMMANDS "${BUILD_COMMANDS}set (SCRIPT_DIR \"${CMAKE_INSTALL_PREFIX}/${RUNTIME_INSTALL_DIRECTORY}\")\n")
    set (BUILD_COMMANDS "${BUILD_COMMANDS}${COMPILE_DEFINITIONS}\n")
    set (BUILD_COMMANDS "${BUILD_COMMANDS}configure_file (\"${SCRIPT_FILE}\" \"${INSTALL_FILE}\" @ONLY)\n")
  else ()
    set (BUILD_COMMANDS "${BUILD_COMMANDS}configure_file (\"${SCRIPT_FILE}\" \"${OUTPUT_FILE}\" COPYONLY)\n")
    if (NOT BASIS_TYPE MATCHES "NOEXEC")
    set (BUILD_COMMANDS "${BUILD_COMMANDS}\nif (UNIX)\n")
    set (BUILD_COMMANDS "${BUILD_COMMANDS}  execute_process (COMMAND chmod +x \"${OUTPUT_FILE}\")\n")
    set (BUILD_COMMANDS "${BUILD_COMMANDS}endif ()\n")
    endif ()
  endif ()

  # write build script only if it differs from previous build script
  #
  # Note: Adding BUILD_SCRIPT to the dependencies of the custom command
  #       caused the custom command to be executed every time even when the
  #       BUILD_SCRIPT file was not modified. Therefore, use dummy output
  #       file which is deleted when the script differs from the previous one.
  #
  # TODO There must be a better solution to this problem.
  file (WRITE "${BUILD_SCRIPT}" "${BUILD_COMMANDS}")

  file (WRITE "${BUILD_SCRIPT}.check" "# DO NOT edit. Automatically generated by BASIS.
execute_process (
  COMMAND \"${CMAKE_COMMAND}\" -E compare_files \"${BUILD_SCRIPT}\" \"${BUILD_SCRIPT}.copy\"
  RESULT_VARIABLE BUILD_SCRIPT_CHANGED
  OUTPUT_QUIET
  ERROR_QUIET
)

if (BUILD_SCRIPT_CHANGED)
  file (REMOVE \"${BUILD_SCRIPT}.copy\")
endif ()"
  )

  # add custom target
  file (RELATIVE_PATH REL "${CMAKE_BINARY_DIR}" "${OUTPUT_FILE}")

  add_custom_command (
    OUTPUT  ${OUTPUT_FILES} "${BUILD_SCRIPT}.copy"
    DEPENDS "${SCRIPT_FILE}"
    COMMAND "${CMAKE_COMMAND}" -P "${BUILD_SCRIPT}"
    COMMAND "${CMAKE_COMMAND}" -E copy "${BUILD_SCRIPT}" "${BUILD_SCRIPT}.copy"
    COMMENT "Building script ${REL}..."
  )

  add_custom_target (
    ${TARGET_UID}-
    COMMAND "${CMAKE_COMMAND}" -P "${BUILD_SCRIPT}.check"
  )

  add_custom_target (
    ${TARGET_UID}+
    DEPENDS ${OUTPUT_FILES}
  )

  add_dependencies (${TARGET_UID}+ ${TARGET_UID}-)
  add_dependencies (${TARGET_UID}  ${TARGET_UID}+)

  # cleanup on "make clean"
  set_property (DIRECTORY APPEND PROPERTY ADDITIONAL_MAKE_CLEAN_FILES ${OUTPUT_FILES})

  # install script
  if (BASIS_TYPE MATCHES "NOEXEC")
    set (WHAT "FILES")
  else ()
    set (WHAT "PROGRAMS")
  endif ()

  install (
    ${WHAT}     "${INSTALL_FILE}"
    RENAME      "${OUTPUT_NAME}"
    DESTINATION "${RUNTIME_INSTALL_DIRECTORY}"
    COMPONENT   "${RUNTIME_COMPONENT}"
  )

  message (STATUS "Adding build command for script ${TARGET_UID}... - done")
endfunction ()

# ****************************************************************************
#! @brief Add scripts with specified extension.
#!
#! This function calls basis_add_script() for each script within the current
#! source directory which has the extension ".EXT" or ".EXT.in".
#!
#! @param [in] EXT  Script extension, e.g., "sh" for shell scripts.
#! @param [in] ARGN This argument list is parsed and the following
#!                  arguments are extracted:
#! @par
#! <table border="0">
#!   <tr>
#!     <td style="white-space:nowrap; vertical-align:top; padding-right:1em">
#!         @b COMPONENT name</td>
#!     <td>Name of the component. See basis_add_script() for default.</td>
#!   </tr>
#! </table>
#!
#! @returns Adds custom build targets for the globbed scritps. To add the
#!          custom targets that actually build the scripts,
#!          basis_add_custom_finalize() has to be invoked.

function (basis_add_scripts_by_extension EXT)
  if (BASIS_VERBOSE)
    file (RELATIVE_PATH DIR "${PROJECT_SOURCE_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}")
    message (STATUS "Adding scripts in ${DIR} with extension .${EXT} or .${EXT}.in")
    set (DIR)
  endif ()

  # parse arguments
  CMAKE_PARSE_ARGUMENTS (ARGN "" "COMPONENT" "" ${ARGN})

  if (ARGN_UNPARSED_ARGUMENTS)
    message ("Unknown arguments given for basis_add_scripts_by_extension (${EXT}): ${ARGN_UNPARSED_ARGUMENTS}")
  endif ()

  if (ARGN_COMPONENT)
    set (COMPONENT "COMPONENT" "${ARGN_COMPONENT}")
  endif ()

  # glob script files with given extension
  file (GLOB FILES RELATIVE "${CMAKE_CURRENT_SOURCE_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}/*")

  # add scripts
  foreach (SCRIPT ${FILES})
    if (NOT IS_DIRECTORY "${SCRIPT}")
      if ("${SCRIPT}" MATCHES ".*\\.${EXT}$|.*\\.${EXT}\\.in$")
        basis_add_script ("${SCRIPT}" ${COMPONENT})
      endif ()
    endif ()
  endforeach ()
endfunction ()

# ****************************************************************************
#! @brief Add scripts with specified extensions.
#!
#! @sa basis_add_scripts_by_extension()
#!
#! @param [in] ARGN This argument list is parsed and the following arguments
#!                  are extracted. All other arguments are considered script
#!                  extension.
#! @par
#! <table border="0">
#!   <tr>
#!     <td style="white-space:nowrap; vertical-align:top; padding-right:1em">
#!         @b COMPONENT name</td>
#!     <td>Name of the component. See basis_add_script() for default.</td>
#!   </tr>
#! </table>
#!
#! @returns Adds custom build targets for the globbed scritps. To add the
#!          custom targets that actually build the scripts,
#!          basis_add_custom_finalize() has to be invoked.

macro (basis_add_scripts_by_extensions)
  # parse arguments
  CMAKE_PARSE_ARGUMENTS (ARGN "" "COMPONENT" "" ${ARGN})

  if (ARGN_COMPONENT)
    set (COMPONENT "COMPONENT" "${ARGN_COMPONENT}")
  endif ()

  # add scripts by extension
  foreach (EXT ${ARGN_UNPARSED_ARGUMENTS})
    basis_add_scripts_by_extension ("${EXT}" ${COMPONENT})
  endforeach ()
endmacro ()

# ****************************************************************************
#! @brief Add scripts with default extensions.
#!
#! This macro adds each script within the current source directory which has
#! a default extension using basis_add_script().
#!
#! Considered default extensions are "sh" for shell scripts, "py" for Python
#! scripts, and "pl" for Perl scripts.
#!
#! \param [in] ARGN This argument list is parsed and the following arguments
#!                  are extracted.
#! @par
#! <table border="0">
#!   <tr>
#!     <td style="white-space:nowrap; vertical-align:top; padding-right:1em">
#!         @b COMPONENT name</td>
#!     <td>Name of the component. See basis_add_script() for default.</td>
#!   </tr>
#! </table>
#!
#! @returns Adds custom build targets for the globbed scritps. To add the
#!          custom targets that actually build the scripts,
#!          basis_add_custom_finalize() has to be invoked.

macro (basis_add_scripts)
  # parse arguments
  CMAKE_PARSE_ARGUMENTS (ARGN "" "COMPONENT" "" ${ARGN})

  if (ARGN_UNPARSED_ARGUMENTS)
    message ("Unknown arguments given for basis_add_scripts (): '${ARGN_UNPARSED_ARGUMENTS}'")
  endif ()

  if (ARGN_COMPONENT)
    set (COMPONENT "COMPONENT" "${ARGN_COMPONENT}")
  endif ()

  # add scripts with known extensions
  basis_add_scripts_by_extension (sh ${COMPONENT}) # shell scripts
  basis_add_scripts_by_extension (py ${COMPONENT}) # python scripts
  basis_add_scripts_by_extension (pl ${COMPONENT}) # Perl scripts
endmacro ()

# ****************************************************************************
#! @brief Fianlize addition of custom targets.
#!
#! This function is called by basis_add_project_finalize() to finalize the
#! addition of the custom build targets such as, for example, build targets
#! to build script files, MATLAB Compiler targets, and MEX script generated
#! MEX-files.
#!
#! @sa basis_add_script_finalize()
#! @sa basis_add_mcc_target_finalize()
#! @sa basis_add_mex_target_finalize()
#!
#! @param [in] ARGN Not used.
#!
#! @returns Adds custom targets that actually build the executables and
#!          libraries for which custom build targets where added by
#!          basis_add_executable(), basis_add_library(), and basis_add_script().
#!
#! @ingroup CMakeUtilities

function (basis_add_custom_finalize)
  foreach (TARGET_UID ${BASIS_TARGETS})
    get_target_property (BASIS_TYPE ${TARGET_UID} "BASIS_TYPE")
    if (BASIS_TYPE MATCHES "SCRIPT")
      basis_add_script_finalize (${TARGET_UID})
    elseif (BASIS_TYPE MATCHES "MEX")
      basis_add_mex_target_finalize (${TARGET_UID})
    elseif (BASIS_TYPE MATCHES "MCC")
      basis_add_mcc_target_finalize (${TARGET_UID})
    endif ()
  endforeach ()
endfunction ()

#! @}
